[meta]
name = "Ultimate Medals Extended"
author = "ArEyeses"
category = "Race"
version = "1.5"

[script]
module = "UltimateMedalsExtended"
shared_exports = [ "Medals/IMedal.as" ]
exports = [ "Exports.as" ]
optional_dependencies = [ "NadeoServices", "MLFeedRaceData" ]
